---
#-------------------------------
# General Site Settings

title: 成大永續放空生活節
logo:
author: 成大永續創新社 x 放空生活節
description: this is meta description
email: 111b089@gs.ncku.edu.tw
phone: +886 0935 677 976
address: 701, 台南市東區大學路1號
copyright: Copyright &copy; 2023 Designed by [Howard](https://github.com/How-Wang) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: 關於我們, link: "/about" }
  - { name: 活動介紹, link: "/blog" }
  - { name: 贊助夥伴, link: "/portfolio" }
  - { name: 聯絡我們, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: 成大<br>永續放空生活節

social:
  - { icon: "ti-facebook", link: "https://www.facebook.com/NCKU.SIC" }
  - { icon: "ti-instagram", link: "https://www.instagram.com/nckusic_toast__.__/" }
  # - { icon: "ti-dribbble", link: "#" }
  # - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: 「讓生活永續，讓心靈放空」是本團隊的核心標語，利用生活中的永續來引起內在動機，讓每個人由內而外自主行動，一同打造更好的社會，也藉由靈性的心靈體驗，去內在放空自我，理解「永續」的不同面貌。此次我們舉辦「成大永續放空生活節」，希望藉由橫向與縱向推廣永續相關知識及議題、放空體驗，達到台南市民與學生的永續意識的提升。

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  
  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "成大永續創新社"
    image: "assets/images/team/sic.png"
    designation: "讓每個人找到自己的永續"

  - title: "世界宗教博物館"
    image: "assets/images/team/mwr.jpg"
    designation: "尊重每一個信仰，包容每一個族群，博愛每一個生命"

  - title: "未來智慧工場"
    image: "assets/images/team/af.png"
    designation: "以未來為題, 在成大, 以大學教育的知識傳遞為基準, 凝視日常生活"

#-------------------------------
# Skills Section

skills-title: SDGs 分佈量
skills:
  - { name: 終結貧窮, color: "#e5243b", value: "90%" }
  - { name: 清除飢餓, color: "#dda63a", value: "60%" }
  - { name: 健康與福祉, color: "#4c9f38", value: "80%" }
  - { name: 優質教育, color: "#c5192d", value: "70%" }
  - { name: 性別平權, color: "#ff3a21", value: "90%" }
  - { name: 淨水與衛生, color: "#26bde2", value: "60%" }
  - { name: 可負擔的潔淨能源, color: "#fcc308", value: "80%" }
  - { name: 合適的工作與經濟成長, color: "#a21942", value: "70%" }
  - { name: 工業化、創新及基礎建設, color: "#fd6925", value: "90%" }
  - { name: 減少不平等, color: "#df1487", value: "60%" }
  - { name: 永續城鄉, color: "#fd9d24", value: "80%" }
  - { name: 責任消費及生產, color: "#bf8b2e", value: "70%" }
  - { name: 氣候行動, color: "#3f7e44", value: "90%" }
  - { name: 保育海洋生態, color: "#0a97d9", value: "60%" }
  - { name: 保育陸域生態, color: "#56c02b", value: "80%" }
  - { name: 和平、正義及健全制度, color: "#00689d", value: "70%" }
  - { name: 多元夥伴關係, color: "#19486a", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: 活動資訊
experience:
  - {
      name: 開幕講座,
      icon: "icon-1.png",
      date: "04/15（六）15:00-16:30",
      organization: "成大未來館二樓",
    }
  - {
      name: 永續市集,
      icon: "icon-2.png",
      date: "05/20 （六）14:00-19:00",
      organization: "成大未來館前廣場",
    }
  - {
      name: 二手市集,
      icon: "icon-3.png",
      date: "05/20 （六）14:00-19:00",
      organization: "成大未來館二樓",
    }
  - {
      name: 共好舞台｜永續拼圖,
      icon: "icon-1.png",
      date: "05/20 （六）14:00-16:00",
      organization: "成大未來館三樓",
    }
  - {
      name: 電影座談,
      icon: "icon-2.png",
      date: "05/20 （六）14:00-16:00",
      organization: "成大未來館三樓",
    }
  - {
      name: 放空舞台｜音樂會 x 專家分享,
      icon: "icon-3.png",
      date: "05/20 （六）15:00-18:00",
      organization: "成大未來館前廣場",
    }
#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Marters in UX Design,
      date: "2006",
      organization: "Masassusets Institute of Technology",
    }
  - {
      name: Honours in Fine Arts,
      date: "2004",
      organization: "Harvard University",
    }
  - {
      name: Higher Secondary Certificat,
      date: "2000",
      organization: "Cardiff School",
    }
  - {
      name: Secondary School Certificate,
      date: "1998",
      organization: "Cardiff School",
    }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: UI Design,
      icon: ti-palette,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: ,# Add true to select section
    }
  - {
      name: UX Design,
      icon: ti-vector,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: true, # Add true to select section
    }
  - {
      name: Interaction Design,
      icon: ti-panel,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
